services:
  _defaults:
    autowire: true
    autoconfigure: true

  # DataFixtures services for dev environment
  Tourze\CmsCollectBundle\DataFixtures\:
    resource: '../../DataFixtures'
    tags: ['doctrine.fixture.orm']